package output;

import analyzer.Analyzer;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.usermodel.charts.ChartLegend;
import org.apache.poi.ss.usermodel.charts.LegendPosition;
import org.apache.poi.xssf.usermodel.*;
import org.apache.poi.xssf.usermodel.charts.XSSFChartLegend;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.*;

/**
 * Class using for output information that generated by {@link Analyzer} class.<br>
 * Now it have only one operation
 */
public class Output {

    public static final String excelFilePath = "./NC_Lab_RESULTS.xlsx";
    private Map<String, Map<String, List<Long>>> result;
    Analyzer analyzer;

    public Output() {

        analyzer = new Analyzer();
        result = new HashMap<>(analyzer.analize());
        createBaseForExcelFile();
    }

    private void createBaseForExcelFile() {

        Workbook workbook = new XSSFWorkbook();

        for (Map.Entry<String, Map<String, List<Long>>> fillers : result.entrySet()) {
            Sheet sheet = workbook.createSheet(fillers.getKey());

            Row headerRow = sheet.createRow(0);

            int iteratorForNameOfColumns = 0;
            Cell zeroCell = headerRow.createCell(iteratorForNameOfColumns);
            zeroCell.setCellValue("Sorter name");

            int length = analyzer.getBeginLength();
            while (length < analyzer.getMaxArrayLength()) {
                iteratorForNameOfColumns++;
                Cell cell = headerRow.createCell(iteratorForNameOfColumns);
                cell.setCellValue(length *= analyzer.getIncreaseValue());
            }

            setDateIntoExcelFile(fillers, sheet);

            for (int i = 0; i < iteratorForNameOfColumns; i++) {
                sheet.autoSizeColumn(i);
            }

        }
        fileOpenAndWrite(workbook);
    }

    private void setDateIntoExcelFile(Map.Entry<String, Map<String, List<Long>>> fillers, Sheet sheet) {
        int rowNumber = 1;

        for (Map.Entry<String, List<Long>> sorters : fillers.getValue().entrySet()) {

            Row row = sheet.createRow(rowNumber++);
            int iteratorForListResults = 0;
            row.createCell(iteratorForListResults).setCellValue(sorters.getKey());

            for (Long resultValue : sorters.getValue()) {
                iteratorForListResults++;
                row.createCell(iteratorForListResults).setCellValue(resultValue);
            }
        }
    }

   /* private void CreateChart(Sheet sheet){
        Drawing drawing = sheet.createDrawingPatriarch();
        ClientAnchor anchor = drawing.createAnchor(0, 0, 0, 0, 0, 5, 10, 15);
        Chart chart = drawing.createChart(anchor);
        ChartLegend legend = chart.getOrCreateLegend();
        legend.setPosition(LegendPosition.BOTTOM);


    }*/

    private void fileOpenAndWrite(Workbook workbook) {
        // Write the output to a file
        try {
            FileOutputStream fileOut = new FileOutputStream(excelFilePath);
            workbook.write(fileOut);
            fileOut.close();

            // Closing the workbook
            workbook.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}