package output;

import analyzer.Analyzer;

/**
 * Class using for output information that generated by {@link Analyzer} class.<br>
 *     Now it have only one operation
 */
public class Output {
    public Output(){

        Analyzer analyzer = new Analyzer();
        analyzer.analize(3);
    }
}